### ISSUE TITLE
Infografía_Antonia Mtz Sandoval

### ISSUE THREAD

**Issue by 2003lulu** [SistemasTecTlaxiaco/actividad-1-infografia-2003lulu-1#1]
[Infografía_Antonia Mtz Sandoval.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-2003lulu-1/files/14250835/Infografia_Antonia.Mtz.Sandoval.pdf)

**Comment by irving1989** [comment]
Partes de la infografía (título, texto explicativo, gráficos, fuente, créditos): **4** - Todas las partes de la infografía se encuentran
Coherencia y pertinencia: **4** - Los elementos gráficos se encuentran relacionados con el tema.
Organización de la información: **3** - El tema está bien desarrollado.
Diseño de la infografía: **4** - Los textos y colores si combinan en armonía.
Creatividad: **3** - El diseño es bueno, pero se encuentra demasiado saturado de texto

Total de puntos: 18/20

**Calificación: 18**

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
